export enum Type {

    ADD_REGISTRATION_REQUEST = 'ADD_REGISTRATION_REQUEST',
    ADD_REGISTRATION_SUCCESS = 'ADD_REGISTRATION_SUCCESS',
    ADD_REGISTRATION_FAILURE = 'ADD_REGISTRATION_FAILURE',
   
  }
