export enum Type {
  CHANGED_MANAGER_INPUT = "CHANGED_MANAGER_INPUT",
  CHANGED_WORKPLACE_INPUT = "CHANGED_WORKPLACE_INPUT",
  CHANGED_PHONE_INPUT = "CHANGED_PHONE_INPUT",
  CHANGED_OWNHOUSE_INPUT = "CHANGED_OWNHOUSE_INPUT"
}
