export enum Type {
  CHANGED_VACCINE_INPUT = "CHANGED_VACCINE_INPUT",
  CHANGED_SICKNESS_INPUT = "CHANGED_SICKNESS_INPUT",
  CHANGED_PASTDISEASE_INPUT = "CHANGED_PASTDISEASE_INPUT",
  CHANGED_TREATMENTS_INPUT = "CHANGED_TREATMENTS_INPUT"
}
